version: "3.8"
services:
 db:
  image: postgres:13
  container_name: movie_db
  environment:
   POSTGRES_DB: ${POSTGRES_DB}
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  ports:
   - "5432:5432"
  volumes:
   - db_data:/var/lib/postgresql/data
   - ./db:/docker-entrypoint-initdb.d
volumes:
 db_data:
